name: Cypress Tests

on:
  push:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  
      - name: Install dependencies
        run: npm install

      - name: Build app (optional)
        run: npm run build  

      - name: Start app
        run: npm run dev & 
        env:
          NODE_ENV: development  
          
      - name: Cypress run
        uses: cypress-io/github-action@v6